#### Working with files in python

In [1]:
# create a file & write some stuff
fileName = 'test.txt'
with open(fileName, 'w') as f:
    story = """
    This is a shit story.
    But it is not a story.
    """
    f.write(story)
    f.close()
    
# read the file
fileContent = ""
with open(fileName, 'r+') as f:
    fileContent = f.read()
    f.close()

# work with contents
fileContent = [x.strip() for x in fileContent.strip().split("\n")]
print(fileContent)

['This is a shit story.', 'But it is not a story.']


#### Working with TOML files


In [2]:
pip install toml

Defaulting to user installation because normal site-packages is not writeable
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [6]:
import toml

tomlFileName="toml_file.toml"
with open(tomlFileName) as f:
    tomlContent = f.read()
    
# parse TOML Contents to dictionary
tomlParser = toml.loads(tomlContent)
print(tomlParser)

# convert TOML dictionary to Toml string
tomlString = toml.dumps(tomlParser)
print(tomlString)


{'title': 'TOML Example', 'owner': {'name': 'Ankush Bhardwaj', 'dob': datetime.datetime(1979, 5, 27, 7, 32, tzinfo=<toml.tz.TomlTz object at 0x7f5ffc720700>)}, 'database': {'server': '192.168.1.1', 'ports': [8001, 8001, 8002], 'connection_max': 5000, 'enabled': True}, 'clients': {'data': [['gamma', 'delta'], [1, 2]]}}
title = "TOML Example"

[owner]
name = "Ankush Bhardwaj"
dob = 1979-05-27T07:32:00-08:00

[database]
server = "192.168.1.1"
ports = [ 8001, 8001, 8002,]
connection_max = 5000
enabled = true

[clients]
data = [ [ "gamma", "delta",], [ 1, 2,],]



#### Working with JSON files

In [12]:
import json
json_string = """
{
    "name": "Ankush Bhardwaj",
    "database": {
        "server": "192.168.1.1",
        "ports": [ 8001, 8001, 8002 ],
        "enabled": "true"
    }
}
"""

# parse json content
jsonParser = json.dumps(json_string)
print(jsonParser)

# decode json content
jsonLoad = json.loads(jsonParser)
print(jsonLoad)

"\n{\n    \"name\": \"Ankush Bhardwaj\",\n    \"database\": {\n        \"server\": \"192.168.1.1\",\n        \"ports\": [ 8001, 8001, 8002 ],\n        \"enabled\": \"true\"\n    }\n}\n"

{
    "name": "Ankush Bhardwaj",
    "database": {
        "server": "192.168.1.1",
        "ports": [ 8001, 8001, 8002 ],
        "enabled": "true"
    }
}



#### Numpy

In [14]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 15.8 MB 1.2 MB/s eta 0:00:01
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [19]:
import numpy as np
np.__version__
# 1D array - vector
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

# 2D array - matrix
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr)
print(arr[0][1])

# ND array - tensor
# initialization
print(np.zeros(2))
print(np.ones(2))
print(np.arange(2, 9, 2))

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(arr)
arr = np.sort(arr)
print(arr)
print(arr.ndim) # dimension
print(arr.size) # length
print(arr.shape) # shape

[1 2 3 4 5 6]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
[0. 0.]
[1. 1.]
[2 4 6 8]
[2 1 5 3 7 4 6 8]
[1 2 3 4 5 6 7 8]
1
8
(8,)


In [ ]:
def binary_search(arr, key):
    s = 0, e = len(arr)-1
    while(s <= e):
        m = s + (e - s)/2
        if arr[m] == key:return m;
        elif arr[m] < key: s = m + 1
        else: e = m - 1